targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/feature/**/domain/model/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/feature/**/domain/model/**.dart
            - lib/feature/**/domain/model/**.freezed.dart
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed (except explicit_to_json).
          # explicit to json changed from default to true
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false