name: comic_book
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  boxy: ^2.0.6+2
  cached_network_image: ^3.2.3
  dio: ^5.0.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^14.2.7
  json_annotation: ^4.7.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.0
  sliver_tools: ^0.2.7
  sqflite: ^2.3.2
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mockito: ^5.3.0

flutter:
  uses-material-design: true
