name: comic_book
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^9.0.3
  json_annotation: ^4.7.0
  boxy: ^2.0.6+2
  sliver_tools: ^0.2.7
  dio: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mockito: ^5.3.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
